esphome:
  name: fishfeeder
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    id: button
    name: "Feeder button"
    pin: 
      number: 4
      inverted: yes
    on_press:
      then:
        - switch.turn_on: relay
        - delay: 1s
        - switch.turn_off: relay
  - platform: gpio
    id: hall
    name: "Feeder origin"
    pin: 
      number: 12
      inverted: yes
    on_press:
      then:
        - switch.turn_off: relay
      
switch:
  - platform: gpio
    id: relay
    name: "Feeder motor"
    pin:
      number: 14
      
status_led:
  pin: 
    number: 5
    inverted: true